apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fallout1

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - web.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: fallout1
  app.kubernetes.io/part-of: fallout1-multiplayer

images:
  - name: fallout1-api
    newTag: latest
  - name: fallout1-web
    newTag: latest
